---
name: Lint Codebase with Ruff

"on":
  push:
  pull_request:

jobs:
  linter-for-suffering:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

      - name: Lint with Ruff
        uses: astral-sh/ruff-action@4919ec5cf1f49eff0871dbcea0da843445b837e6
        with:
          args: "check --config ruff.toml"
