---
name: Example

"on":
  push:
    branches: [main]
    paths:
        - .github/workflows/publish-aws.yml
        - packages/binaryrain_helper_cloud_aws/**

jobs:
  uv-publish:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Build the package
        run: uv build --package binaryrain_helper_cloud_aws --no-sources

      - name: Publish the package
        run: uv publish --token ${{ secrets.PYPI_TOKEN }}
