---
name: Publish Toolkit - AWS

"on":
  push:
    branches: [main]
    paths:
      - .github/workflows/publish-aws.yml
      - packages/binaryrain_helper_cloud_aws/**

env:
  WORKING_DIRECTORY: packages/binaryrain_helper_cloud_aws
  PACKAGE_NAME: binaryrain_helper_cloud_aws

jobs:
  uv-publish:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: uv sync --all-extras --dev

      - name: Build the package
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: uv build --package ${{ env.PACKAGE_NAME }} --no-sources

      - name: Publish the package
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: uv publish --token ${{ secrets.PYPI_TOKEN }}
