---
name: Publish Toolkit - DATAFRAME

"on":
  push:
    branches: [main]
    paths:
      - packages/binaryrain_helper_data_processing/**

env:
  WORKING_DIRECTORY: packages/binaryrain_helper_data_processing
  PACKAGE_NAME: binaryrain_helper_data_processing

jobs:
  uv-publish:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@3259c6206f993105e3a61b142c2d97bf4b9ef83d

      - name: Check Ruff
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: uvx ruff check .

      - name: Install the project
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: uv sync --all-extras --dev

      - name: Build the package
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: uv build --package ${{ env.PACKAGE_NAME }} --no-sources

      - name: Publish the package
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: uv publish --token ${{ secrets.PYPI_TOKEN }}
